### ISSUE TITLE
Deploy basic release trigger workflow

### ISSUE THREAD

**Issue by philnewm** [ynput/ops-repo-automation#2]
### Checklist
- [X] Create automation repo
- [X] Create issues for any release trigger related tasks or ideas
- [X] Define feature set for basic release trigger implementation 
- [X] Cleanup release trigger to allow basic implementation
- [X] Setup and document expected repo variables
- [X] Fix Bugs in [Github-Query Action](https://github.com/ynput/github-query)
- [X] Verify functionality in testing repo
- [X] Add in early return checks for variabales
- [X] Fix version increment issue
- [X] Test on actual addon repo
- [X] Fix secrets check issue 
- [X] Fix label list conversion from gh output
- [X] Fix branch protection errors
- [X] Fix tag wasn't created
- [X] Fix prevent commiting zip package to main
- [X] Fix test repo reset workflow 
- [X] Fix develop version bump is missing
- [X] Fix merge issues in merging to main
- [X] Fix update-develop only got changes in package.py
- [X] Add .zip from source
- [X] Discuss develop version bumping 
- [x] Create first workflow release

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Since release are curretnly created completly manual a release trigger workflow is in development.
Right not it looks pretty much like the scope of implementing all the requests and ideas at once is just too big since it's still not finished.

It would make sense to strip out some of the still buggy behavior, release a basic version to test the whole infrastructure on github first. See if adjustements are needed rgiht away.
Afterwards move on to a rolling release cycle to update the feature set step by step while the general structure for roll outs is in place already.

### How would you imagine the implementation of the feature?

**Features for the Basic version**
* Query GitHub release information
* Increment version
* Update tag
* Merge to main
* Build from main
* Update develop
* Create release
* verify release (based on tag)

**Missing features for basic version**
* Query PR information
* Convert PR information to usable strings
* Include PR information in release
* Implement PR format check workflow

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the feature request.

### Additional context:

Developing such complex automations in one go doesn't seem so usefull since adjsutements will be neccessary down th eline anyway.
A rolling release just makes way more sense here.

**Comment by mkolar** [comment]
@philnewm this seems done to me. can we close it?

**Comment by philnewm** [comment]
Yes, I forgot
